### PR TITLE
Fix delete PV annotations.

### LINKED ISSUE #199: deletePVAnnotations deletes PVC annotations instead of PV annotations
deletePVAnnotations needs to remove annotations on PVs rather than on PVCs. We already have deletePVCAnnotations to deal with PVC deletion.

https://github.com/fusor/mig-controller/blob/29391193fe710575ced68dae4747a3f1a8728347/pkg/controller/migmigration/annotation.go#L353

### PR DESCRIPTION
**Pull request by jortel**
fixes #199

Also corrected comments and renaming for consistency.

### CODE REVIEW

File: pkg/controller/migmigration/annotation.go [hunk 1]
```diff
@@ -60,7 +60,7 @@ func (t *Task) annotateStageResources() error {
 		return err
 	}
 	// PV & PVCs
-	err = t.annotatePvs(client)
+	err = t.annotatePVs(client)
```
Comment (jortel) [inline pkg/controller/migmigration/annotation.go]: unrelated: renamed for consistency.

**Comment by Danil-Grigorev** [comment]
run tests
