### PR TITLE
Fix postpone message seconds.

### LINKED ISSUE #241: Postpone message not in seconds.  Validate postpone logic.
I deployed our mssql workload and started a Stage before I had created the custom scc (https://github.com/fusor/mig-agnosticd/blob/master/demos/2019_07_Hackfest/files/mssql-scc.yaml)

The stage failed 

```
from{"level":"info","ts":1565108784.4268792,"logger":"migration|5zcdg","msg":"Migration [RUN]","name":"2326a590-b85f-11e9-9fa9-ab1e3b5868a5","stage":true,"phase":"StageRestoreFailed"}
{"level":"error","ts":1565108784.6178524,"logger":"migration|5zcdg","msg":"","error":"pods \"mssql-deployment-1-482jm-stage\" is forbidden: unable to validate against any security context constraint: []","stacktrace":"github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Error\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:59\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Trace\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:65\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).deletePodAnnotations\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/annotation.go:353\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).deleteAnnotations\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/annotation.go:302\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).Run\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/task.go:438\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).migrate\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migrate.go:77\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).Reconcile\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migmigration_controller.go:168\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

I created the scc and then clicked Stage a 2nd time to kick it off again.
Not seeing any status updates on webui

Screen Shot 2019-08-06 at 12 29 15 PM

Looking at the migmigration

```
$ oc get migmigrations 45adc870-b867-11e9-9fa9-ab1e3b5868a5 -o yaml
apiVersion: migration.openshift.io/v1alpha1
kind: MigMigration
metadata:
  annotations:
    touch: 3ddaee07-8a74-49f4-8ddb-419851382802
  creationTimestamp: "2019-08-06T16:28:50Z"
  generation: 2
  name: 45adc870-b867-11e9-9fa9-ab1e3b5868a5
  namespace: mig
  resourceVersion: "104871"
  selfLink: /apis/migration.openshift.io/v1alpha1/namespaces/mig/migmigrations/45adc870-b867-11e9-9fa9-ab1e3b5868a5
  uid: 45b93bee-b867-11e9-b619-0a269a138426
spec:
  migPlanRef:
    name: mssql01
    namespace: mig
  stage: true
status:
  conditions:
  - category: Critical
    lastTransitionTime: "2019-08-06T16:28:50Z"
    message: Postponed 10000000000 seconds to ensure migrations run serially and in
      order.
    status: "True"
    type: Postponed

```

The original migmigration stage that failed is:

```
$ oc  get migmigration 2326a590-b85f-11e9-9fa9-ab1e3b5868a5 -o yaml
apiVersion: migration.openshift.io/v1alpha1
kind: MigMigration
metadata:
  annotations:
    touch: e8653664-89bb-40e3-bff2-ebfa25c42982
  creationTimestamp: "2019-08-06T15:30:36Z"
  generation: 14
  name: 2326a590-b85f-11e9-9fa9-ab1e3b5868a5
  namespace: mig
  resourceVersion: "89832"
  selfLink: /apis/migration.openshift.io/v1alpha1/namespaces/mig/migmigrations/2326a590-b85f-11e9-9fa9-ab1e3b5868a5
  uid: 234225eb-b85f-11e9-b619-0a269a138426
spec:
  migPlanRef:
    name: mssql01
    namespace: mig
  stage: true
status:
  conditions:
  - category: Required
    lastTransitionTime: "2019-08-06T15:30:36Z"
    message: The migration is ready.
    status: "True"
    type: Ready
  - category: Advisory
    durable: true
    lastTransitionTime: "2019-08-06T15:32:31Z"
    message: 'The migration has failed.  See: Errors.'
    reason: StageRestoreFailed
    status: "False"
    type: Failed
  errors:
  - 'Restore: mig/2326a590-b85f-11e9-9fa9-ab1e3b5868a5-6cn2f partially failed.'
  phase: StageRestoreFailed
  startTimestamp: "2019-08-06T15:30:36Z"

```

### PR DESCRIPTION
**Pull request by jortel**
fixes #241

### CODE REVIEW

File: pkg/controller/migmigration/migmigration_controller.go [hunk 1]
```diff
@@ -218,7 +218,7 @@ func (r *ReconcileMigMigration) postpone(migration *migapi.MigMigration) (time.D
 	// Pending migrations.
 	pending := []types.UID{}
 	for _, m := range migrations {
-		if !m.Status.HasAnyCondition(Succeeded, Failed) {
+		if m.Status.Phase != Completed {
```
Comment (jortel) [inline pkg/controller/migmigration/migmigration_controller.go]: Unrelated: More straight forward.
