### PR TITLE
Fix unknown kind on 3.7 quiesce.

### LINKED ISSUE #293: Bug 1747922   Quiescing applications on 3.7 failing....
Looks like the controller searches for a Deployment and other resources API version that is too new for OCP 3.7 when attempting to quiesce apps.... below the stacktrace with the errors for each (sock-shop demo test) : 
```
{"level":"info","ts":1567042797.8340664,"logger":"migration|tjn6l","msg":"Migration [RUN]","name":"sock-shop-mig-1567042603","stage":false,"phase":"EnsureStagePods"}
{"level":"info","ts":1567042798.1414194,"logger":"migration|krjnt","msg":"Migration [RUN]","name":"sock-shop-mig-1567042603","stage":false,"phase":"QuiesceApplications"}
{"level":"error","ts":1567042798.4398875,"logger":"migration|krjnt","msg":"","error":"no matches for kind \"Deployment\" in version \"apps/v1\"","stacktrace":"github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Error\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:59\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Trace\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:65\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).scaleDownDeployments\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/quiesce.go:88\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).quiesceApplications\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/quiesce.go:24\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).Run\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/task.go:253\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).migrate\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migrate.go:77\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).Reconcile\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migmigration_controller.go:190\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"error","ts":1567042798.439995,"logger":"migration|krjnt","msg":"","error":"no matches for kind \"StatefulSet\" in version \"apps/v1\"","stacktrace":"github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Error\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:59\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Trace\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:65\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).scaleDownStatefulSets\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/quiesce.go:118\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).quiesceApplications\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/quiesce.go:28\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).Run\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/task.go:253\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).migrate\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migrate.go:77\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).Reconcile\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migmigration_controller.go:190\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"error","ts":1567042798.440047,"logger":"migration|krjnt","msg":"","error":"no matches for kind \"ReplicaSet\" in version \"apps/v1\"","stacktrace":"github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Error\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:59\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Trace\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:65\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).scaleDownReplicaSets\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/quiesce.go:147\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).quiesceApplications\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/quiesce.go:32\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).Run\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/task.go:253\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).migrate\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migrate.go:77\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).Reconcile\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migmigration_controller.go:190\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"error","ts":1567042798.4400983,"logger":"migration|krjnt","msg":"","error":"no matches for kind \"DaemonSet\" in version \"apps/v1\"","stacktrace":"github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Error\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:59\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Trace\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:65\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).scaleDownDaemonSets\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/quiesce.go:181\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).quiesceApplications\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/quiesce.go:36\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).Run\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/task.go:253\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).migrate\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migrate.go:77\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).Reconcile\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migmigration_controller.go:190\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1567042798.451582,"logger":"migration|c5b6s","msg":"Migration [RUN]","name":"sock-shop-mig-1567042603","stage":false,"phase":"EnsureQuiesced"}
{"level":"info","ts":1567042798.9472802,"logger":"migration|sb59p","msg":"Migration [RUN]","name":"sock-shop-mig-1567042603","stage":false,"phase":"EnsureQuiesced"}
```
I know that Deployments were at apps/v1beta1 in 3.7, not sure about the rest of resources but at a minimum we have to be able to comply with OCP 3.7 for all....
We had a similar API issue when deploying the e2e robot-shop test on OCP 3.7 : 
https://github.com/fusor/mig-demo-apps/pull/9

The controller never gets out of quiescing : 
```
Name:         sock-shop-mig-1567042603
Namespace:    openshift-migration
Labels:       controller-tools.k8s.io=1.0
Annotations:  touch=20d58727-873b-4bac-8ad6-dca5ac7eae88
API Version:  migration.openshift.io/v1alpha1
Kind:         MigMigration
Metadata:
  Creation Timestamp:  2019-08-29T01:39:05Z
  Generation:          9
  Owner References:
    API Version:     migration.openshift.io/v1alpha1
    Kind:            MigPlan
    Name:            sock-shop-migplan-1567042603
    UID:             7c3baa1a-c9fd-11e9-a35f-067cf83bca53
  Resource Version:  175317
  Self Link:         /apis/migration.openshift.io/v1alpha1/namespaces/openshift-migration/migmigrations/sock-shop-mig-1567042603
  UID:               c9a21882-c9fd-11e9-a35f-067cf83bca53
Spec:
  Mig Plan Ref:
    Name:        sock-shop-migplan-1567042603
    Namespace:   openshift-migration
  Quiesce Pods:  true
  Stage:         false
Status:
  Conditions:
    Category:              Advisory
    Last Transition Time:  2019-08-29T01:39:58Z
    Message:               Step: 13/27
    Reason:                EnsureQuiesced
    Status:                True
    Type:                  Running
    Category:              Required
    Last Transition Time:  2019-08-29T01:39:05Z
    Message:               The migration is ready.
    Status:                True
    Type:                  Ready
  Phase:                   EnsureQuiesced
  Start Timestamp:         2019-08-29T01:39:05Z
Events:                    <none>
```

### PR DESCRIPTION
**Pull request by jortel**
Fix unknown kind on 3.7 quiesce for: Deployment,StatefulSet, ReplicaSet, DaemonSet, CronJob.  Also noticed during testing that `quiesceApplications()` was logging errors but not return them so the reconcile() did not fail and retry.

Tested on OCP 3.7 and 3.11.

fixes #293

### CODE REVIEW

File: pkg/controller/migmigration/quiesce.go [hunk 1]
```diff
@@ -207,7 +217,40 @@ func (t *Task) scaleDownDaemonSets(client k8sclient.Client) error {
...
-		list := batchv1beta1.CronJobList{}
+		list := batchv1b1.CronJobList{}
+		options := k8sclient.InNamespace(ns)
+		err := client.List(
+			context.TODO(),
+			options,
+			&list)
+		if err != nil {
+			if reflect.TypeOf(err) == reflect.TypeOf(&meta.NoKindMatchError{}) {
+				return t.suspendAlphaCronJobs(client)
```
Comment (jortel) [inline pkg/controller/migmigration/quiesce.go]: Since the _types_ for each API version are completely different (go) structures, I don't know of a more elegant way to deal with this.  Also, there does not seem to be `errors.IsNoKindMatchError()`.

File: pkg/controller/migmigration/quiesce.go [hunk 2]
```diff
@@ -20,6 +24,7 @@ func (t *Task) quiesceApplications() error {
 	err = t.suspendCronJobs(client)
 	if err != nil {
 		log.Trace(err)
+		return err
```
Comment (sseago) [inline pkg/controller/migmigration/quiesce.go]: Was the change in behavior intentional here? We now don't even try to quiesce any other resource type once one type gives us an error. Previously if CronJob suspend failed we'd still try to scale down Deployments, etc. I'm not sure which approach is better overall, but if there is some fundamental problem with scaling down CronJobs in a particular cluster, we'll now never scale down pods at all. That said, it looks like the old error handling was somewhat broken, since if one type returned an error, that error got swallowed by the next scaleDown call. If we want to preserve prior behavior, we'll need to build up an errors slice.

File: pkg/controller/migmigration/quiesce.go (hunk 1 above)
Comment (sseago) [reply pkg/controller/migmigration/quiesce.go]: It seems that there *ought* to be a way to determine the API version of the resource by inspection -- since the API version is available on the resource, but yeah, off the top of my head I don't know how you'd do it given the need to have a struct available ahead of time, unless you want to use one of the more generic API calls that returns an unstructured item rather than stuffing it into the API-defined struct.

Comment (sseago) [reply pkg/controller/migmigration/quiesce.go]: Actually, the answer may just be to pass in a runtime.Unstructured into client.List. Here's the List code:
```
func (c *client) List(ctx context.Context, opts *ListOptions, obj runtime.Object) error {
        _, ok := obj.(*unstructured.UnstructuredList)
        if ok {
                return c.unstructuredClient.List(ctx, opts, obj)
        }
        return c.typedClient.List(ctx, opts, obj)
```

Comment (sseago) [reply pkg/controller/migmigration/quiesce.go]: I guess you'll have to indicate the type in the options, but then you can verify API version and then convert it to the appropriate structured resource.

File: pkg/controller/migmigration/quiesce.go (hunk 2 above)
Comment (sseago) [reply pkg/controller/migmigration/quiesce.go]: Actually, nevermind that. We probably do want to fail on one error. If even one of these fails, then the ensure step will fail forever anyway.

File: pkg/controller/migmigration/quiesce.go (hunk 1 above)
Comment (jortel) [reply pkg/controller/migmigration/quiesce.go]: I don't see any easy way to convert to the the appropriate structured resource.  The `UnstructuredList.Items` contains `Unstructured` which contains an `Objcet` of type: `map[string]interface{}`.  So, it's not like we can switch based on the API version and _cast_ to the appropriate structured type. Even if it could be _cast_, the v2alpha1 and v1beta1 (Go) types are completely different (no inheritance) so the updating (suspend=true) code would need to be duplicated.

I included a commit with an `unstructured` impl.  It's _cringy_, IMHO, but works and luckily we don't need to do this anywhere else (so far).
